/*
    Author:     zmofun      
    HomePage:   http://zmofun.yeah.net
    CopyRight:  All rights reserved.
    Date:       2000.3
*/

#define KEYEsc 0x11b
#define KEYa 0x1e61
#define KEYb 0x3062
#define KEYc 0x2e63
#define KEYd 0x2064
#define KEYe 0x1265
#define KEYf 0x2166
#define KEYg 0x2267
#define KEYh 0x2368
#define KEYi 0x1769
#define KEYj 0x246a
#define KEYk 0x256b
#define KEYl 0x266c
#define KEYm 0x326d
#define KEYn 0x316e
#define KEYo 0x186f
#define KEYp 0x1970
#define KEYq 0x1071
#define KEYr 0x1372
#define KEYs 0x1f73
#define KEYt 0x1474
#define KEYu 0x1675
#define KEYv 0x2f76
#define KEYw 0x1177
#define KEYx 0x2d78
#define KEYy 0x1579
#define KEYz 0x2c7a
#define KEYA 0x1e41
#define KEYB 0x3042
#define KEYC 0x2e43
#define KEYD 0x2044
#define KEYE 0x1245
#define KEYF 0x2146
#define KEYG 0x2247
#define KEYH 0x2348
#define KEYI 0x1749
#define KEYJ 0x244a
#define KEYK 0x254b
#define KEYL 0x264c
#define KEYM 0x324d
#define KEYN 0x314e
#define KEYO 0x184f
#define KEYP 0x1950
#define KEYQ 0x1051
#define KEYR 0x1352
#define KEYS 0x1f53
#define KEYT 0x1454
#define KEYU 0x1655
#define KEYV 0x2f56
#define KEYW 0x1157
#define KEYX 0x2d58
#define KEYY 0x1559
#define KEYZ 0x2c5a
#define KEYCtrl_a       0x1e01
#define KEYCtrl_b       0x3002
#define KEYCtrl_c       0x2e03
#define KEYCtrl_d       0x2004
#define KEYCtrl_e       0x1205
#define KEYCtrl_f       0x2106
#define KEYCtrl_g       0x2207
#define KEYCtrl_h       0x2308
#define KEYCtrl_i       0x1709
#define KEYCtrl_j       0x240a
#define KEYCtrl_k       0x250b
#define KEYCtrl_l       0x260c
#define KEYCtrl_m       0x320d
#define KEYCtrl_n       0x310e
#define KEYCtrl_o       0x180f
#define KEYCtrl_p       0x1910
#define KEYCtrl_q       0x1011
#define KEYCtrl_r       0x1312
#define KEYCtrl_s       0x1f13
#define KEYCtrl_t       0x1414
#define KEYCtrl_u       0x1615
#define KEYCtrl_v       0x2f16
#define KEYCtrl_w       0x1117
#define KEYCtrl_x       0x2d18
#define KEYCtrl_y       0x1519
#define KEYCtrl_z       0x2c1a
#define KEYAlt_a       0x1e00
#define KEYAlt_b       0x3000
#define KEYAlt_c       0x2e00
#define KEYAlt_d       0x2000
#define KEYAlt_e       0x1200
#define KEYAlt_f       0x2100
#define KEYAlt_g       0x2200
#define KEYAlt_h       0x2300
#define KEYAlt_i       0x1700
#define KEYAlt_j       0x2400
#define KEYAlt_k       0x2500
#define KEYAlt_l       0x2600
#define KEYAlt_m       0x3200
#define KEYAlt_n       0x3100
#define KEYAlt_o       0x1800
#define KEYAlt_p       0x1900
#define KEYAlt_q       0x1000
#define KEYAlt_r       0x1300
#define KEYAlt_s       0x1f00
#define KEYAlt_t       0x1400
#define KEYAlt_u       0x1600
#define KEYAlt_v       0x2f00
#define KEYAlt_w       0x1100
#define KEYAlt_x       0x2d00
#define KEYAlt_y       0x1500
#define KEYAlt_z       0x2c00
#define KEY1 0x231
#define KEY2 0x332
#define KEY3 0x433
#define KEY4 0x534
#define KEY5 0x635
#define KEY6 0x736
#define KEY7 0x837
#define KEY8 0x938
#define KEY9 0xa39
#define KEY0 0xb30
#define KEYb1        0x2960    /* ` */
#define KEYa0        0xc2d     /* - */
#define KEYa1        0xd3d     /* = */
#define KEYa2        0x2b5c    /* \ */
#define KEYBackspace  0xe08
#define KEYtab        0xf09
#define KEYReturn        0x1c0d
#define KEYEnter         0x1c0d
#define KEYInsert        0x5200
#define KEYHome        0x4700
#define KEYPageUp        0x4900
#define KEYDelete        0x5300
#define KEYEnd        0x4f00
#define KEYPageDown       0x5100
#define KEYUp        0x4800
#define KEYLeft        0x4b00
#define KEYDown        0x5000
#define KEYRight        0x4d00
#define KEYNUM00        0x352f   /* / */
#define KEYNUM01        0x372a   /* * */
#define KEYNUM02        0x4a2d   /* - */
#define KEYNUM03        0x4e2b   /* + */
#define KEYNUMReturn     0x1c0d
#define KEYNUM1 0x4f31
#define KEYNUM2 0x5032
#define KEYNUM3 0x5133
#define KEYNUM4 0x4b34
#define KEYNUM5 0x4c35
#define KEYNUM6 0x4d36
#define KEYNUM7 0x4737
#define KEYNUM8 0x4838
#define KEYNUM9 0x4939
#define KEYNUM0 0x5230
#define KEYNUMHome        0x532e
#define KEYNUMUp        0x4f00
#define KEYNUMPageup        0x5000
#define KEYNUMLeft        0x5100
#define KEYNUMSpace        0x4b00
#define KEYNUMRight        0x4d00
#define KEYNUMEnd        0x4700
#define KEYNUMDown        0x4800
#define KEYNUMPageDown        0x4900
#define KEYNUMIns        0x5200
#define KEYNUMDelete        0x5300
#define KEY_00 /*~*/        0x297e
#define KEY_01 /*!*/        0x221
#define KEY_02 /*@*/        0x340
#define KEY_03 /*#*/        0x423
#define KEY_04 /*$*/        0x524
#define KEY_05 /*%*/        0x625
#define KEY_06 /*^*/        0x75e
#define KEY_07 /*&*/        0x826
#define KEY_08 /***/        0x92a
#define KEY_09 /*(*/        0xa28
#define KEY_010 /*)*/        0xb29
#define KEY_011 /*_*/        0xc5f
#define KEY_012 /*+*/        0xd2b
#define KEY_013 /*|*/        0x2b7c
#define KEYF1        0x3b00
#define KEYF2        0x3c00
#define KEYF3       0x3d00
#define KEYF4        0x3e00
#define KEYF5        0x3f00
#define KEYF6        0x4000
#define KEYF7        0x4100
#define KEYF8        0x4200
#define KEYF9        0x4300
#define KEYF10        0x4400
#define KEYAlt_F1        0x6800
#define KEYAlt_F2        0x6900
#define KEYAlt_F3        0x6a00
#define KEYAlt_F4        0x6b00
#define KEYAlt_F5        0x6c00
#define KEYAlt_F6        0x6d00
#define KEYAlt_F7        0x6e00
#define KEYAlt_F8        0x6f00
#define KEYAlt_F9        0x7000
#define KEYAlt_F10        0x7100
#define KEYShift_F1        0x5400
#define KEYShift_F2        0x5500
#define KEYShift_F3        0x5600
#define KEYShift_F4        0x5700
#define KEYShift_F5        0x5800
#define KEYShift_F6        0x5900
#define KEYShift_F7        0x5a00
#define KEYShift_F8        0x5b00
#define KEYShift_F9        0x5c00
#define KEYShift_F10        0x5d00
#define KEYCtrl_F1        0x5e00
#define KEYCtrl_F2        0x5f00
#define KEYCtrl_F3        0x6000
#define KEYCtrl_F4        0x6100
#define KEYCtrl_F5        0x6200
#define KEYCtrl_F6        0x6300
#define KEYCtrl_F7        0x6400
#define KEYCtrl_F8        0x6500
#define KEYCtrl_F9        0x6600
#define KEYCtrl_F10        0x6700
#define KEY_d1        0x332c  /* , */
#define KEY_d2        0x342e  /* . */
#define KEY_d3        0x352f  /* / */
#define KEYShift_d1        0x333c  /* < */
#define KEYShift_d2        0x343e  /* > */
#define KEYShift_d3        0x353f  /* ? */
#define KEYCtrl_Alt_a        0x1e00
#define KEYCtrl_Alt_b        0x3000
#define KEYCtrl_Alt_c        0x2e00
#define KEYCtrl_Alt_d        0x2000
#define KEYCtrl_Alt_e        0x1200
#define KEYCtrl_Alt_f        0x2100
#define KEYCtrl_Alt_g        0x2200
#define KEYCtrl_Alt_h        0x2300
#define KEYCtrl_Alt_i        0x1700
#define KEYCtrl_Alt_j        0x2400
#define KEYCtrl_Alt_k        0x2500
#define KEYCtrl_Alt_l        0x2600
#define KEYCtrl_Alt_m        0x3200
#define KEYCtrl_Alt_n        0x3100
#define KEYCtrl_Alt_o        0x1800
#define KEYCtrl_Alt_p        0x1900
#define KEYCtrl_Alt_q        0x1000
#define KEYCtrl_Alt_r        0x1300
#define KEYCtrl_Alt_s        0x1f00
#define KEYCtrl_Alt_t        0x1400
#define KEYCtrl_Alt_u        0x1600
#define KEYCtrl_Alt_v        0x2f00
#define KEYCtrl_Alt_w        0x1100
#define KEYCtrl_Alt_x        0x2d00
#define KEYCtrl_Alt_y        0x1500
#define KEYCtrl_Alt_z        0x2c00
